In [3]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [4]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

Full of single value

In [6]:
np.full((2, 3), 7)

array([[7, 7, 7],
       [7, 7, 7]])

Identity Matrix

In [7]:
np.eye(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

Add  2 in each number of matrix after the first number

In [8]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [9]:
np.arange(0, 100, 9)

array([ 0,  9, 18, 27, 36, 45, 54, 63, 72, 81, 90, 99])

Give equal space between each number

In [10]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [11]:
arr = np.array([[10, 20, 30], [40, 50, 60]])

print("Shape:", arr.shape)   # (2, 3) → 2 rows, 3 columns
print("Size:", arr.size)     # 6 → total elements
print("Dimensions:", arr.ndim) # 2 → 2D array
print("Data type:", arr.dtype) # int64 (or int32 on Windows)

Shape: (2, 3)
Size: 6
Dimensions: 2
Data type: int64


Explicit Type

In [16]:
arr = np.array([[10, 20, 30], [40, 50, 60]],dtype='float32')
print(arr,arr.dtype) 

[[10. 20. 30.]
 [40. 50. 60.]] float32


In [21]:
n=arr.astype('float64')
print(n)


[[10. 20. 30.]
 [40. 50. 60.]]


In [22]:
n.dtype

dtype('float64')

In [23]:
arr.dtype

dtype('float32')