In [4]:
import numpy as np
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90], [100, 110, 120]])


In [5]:
arr

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [ 70,  80,  90],
       [100, 110, 120]])

In [6]:
flat=arr.flatten()
flat

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120])

In [7]:
flat[0]

np.int64(10)

In [8]:
flat[6]

np.int64(70)

In [9]:
flat[0:6]

array([10, 20, 30, 40, 50, 60])

In [11]:
flat[0:6:2]


array([10, 30, 50])

In [12]:
flat

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120])

In [13]:
b = flat[3:7]
b

array([40, 50, 60, 70])

In [14]:
b[0]=999
b

array([999,  50,  60,  70])

In [15]:
flat

array([ 10,  20,  30, 999,  50,  60,  70,  80,  90, 100, 110, 120])

Fancy indexing

In [19]:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120])

In [20]:
arr[[1,4,6]]

array([20, 50, 70])

Boolean Masking

In [4]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120])
arr[arr>50]

array([ 60,  70,  80,  90, 100, 110, 120])