In [1]:
import numpy as np

arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])

print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [2]:
arr[0]

array([1, 2, 3])

In [3]:
np.sum(arr, axis=0)

array([12, 15, 18])

In [4]:
np.sum(arr, axis=1)

array([ 6, 15, 24])

In [5]:
arr[0:2, 1:3]

array([[2, 3],
       [5, 6]])

3D Array

In [ ]:
arr3D = np.array([[[1, 2, 3], [4, 5, 6]],
                  [[7, 8, 9], [10, 11, 12]]])
print(arr3D.shape)

(2, 2, 3)


In [7]:
print(arr3D[0, 1, 2])  

print(arr3D[:, 0, :])   

6
[[1 2 3]
 [7 8 9]]


In [8]:
arr3D[:,0,:]=0
arr3D

array([[[ 0,  0,  0],
        [ 4,  5,  6]],

       [[ 0,  0,  0],
        [10, 11, 12]]])